# Generated by Django 3.1.7 on 2021-04-25 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_auto_20210422_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='tool2_temperature',
            new_name='tool1_temperature',
        ),
    ]
