# Generated by Django 3.1.7 on 2021-05-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('printer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('print', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('pause', models.BooleanField(default=False)),
                ('home', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GcodeFile',
            fields=[
                ('gcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('gcode_name', models.CharField(max_length=100)),
                ('gcode_url', models.URLField(max_length=100)),
                ('gcode_safepath', models.CharField(max_length=100)),
                ('gcode_printed', models.BooleanField(default=False)),
                ('gcode_selected', models.BooleanField(default=False)),
                ('gcode_printing', models.BooleanField(default=False)),
                ('gcode_printfailed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredPrinter',
            fields=[
                ('printer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('gcodefile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                   related_name='print', serialize=False, to='app.gcodefile')),
                ('estimatedPrintTime', models.IntegerField(blank=True, default=0, null=True)),
                ('completion', models.FloatField(blank=True, default=0, null=True)),
                ('printTime', models.IntegerField(blank=True, default=0, null=True)),
                ('printTimeLeft', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('printer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('operational', models.BooleanField(default=False)),
                ('printing', models.BooleanField(default=False)),
                ('cancelling', models.BooleanField(default=False)),
                ('pausing', models.BooleanField(default=False)),
                ('resuming', models.BooleanField(default=False)),
                ('finishing', models.BooleanField(default=False)),
                ('closedOrError', models.BooleanField(default=True)),
                ('error', models.BooleanField(default=False)),
                ('paused', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('tool0_temperature', models.IntegerField(blank=True, default=0, null=True)),
                ('tool1_temperature', models.IntegerField(blank=True, default=0, null=True)),
                ('bed_temperature', models.IntegerField(blank=True, default=0, null=True)),
                ('current_print',
                 models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                      related_name='not_used', to='app.print')),
            ],
        ),
    ]
