# Generated by Django 3.1.7 on 2021-04-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a', models.CharField(max_length=10)),
                ('value_b', models.FloatField(max_length=10)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GcodeFile',
            fields=[
                ('gcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('gcode_name', models.CharField(max_length=100)),
                ('gcode_url', models.URLField(max_length=100)),
                ('gcode_safepath', models.CharField(max_length=100)),
                ('gcode_printed', models.CharField(max_length=10)),
                ('gcode_selected', models.CharField(max_length=10)),
                ('gcode_printer_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('printer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_operational', models.CharField(max_length=10)),
                ('is_printing', models.CharField(max_length=10)),
                ('is_cancelling', models.CharField(max_length=10)),
                ('is_closed_or_error', models.CharField(max_length=10)),
                ('is_paused', models.CharField(max_length=10)),
                ('is_pausing', models.CharField(max_length=10)),
                ('is_ready', models.CharField(max_length=10)),
            ],
        ),
    ]
