# Generated by Django 3.1.7 on 2021-04-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registered_printer',
            fields=[
                ('printer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
