# Generated by Django 3.1.7 on 2021-05-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcodefile',
            name='gcode_printer_id',
            field=models.CharField(blank=True, default='no', max_length=100, null=True),
        ),
    ]
