# Generated by Django 3.1.7 on 2021-05-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('printer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('print', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('pause', models.BooleanField(default=False)),
            ],
        ),
    ]
