# Generated by Django 3.1.7 on 2021-05-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
