# Generated by Django 3.1.7 on 2021-04-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registered_printer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registered_printer',
            new_name='RegisteredPrinter',
        ),
    ]
